# First and second derivative of FNN with respect to input (tensorflow)

Import necessary packages.

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
#tf.keras.backend.set_floatx('float32')

Define activation function and its derivatives.

In [3]:
# Custom activation function
# from keras.layers import Activation
# from keras import backend as K
# from keras.utils.generic_utils import get_custom_objects

#def mσ(x):
    #return np.abs(x) + np.log(1. + np.exp(-2. * np.abs(x)))
    
def mσ(x):
    return tf.math.divide(1., 1. + tf.math.exp(tf.math.negative(x)))

# get_custom_objects().update({'custom_activation': Activation(mσ)})


In [4]:
#def mdσ(x):
    #return np.tanh(x)
    
    
#def md2σ(x):
    #return np.divide(1., np.square(np.cosh(x)))

def mdσ(x):
    return mσ(x) * (1. - mσ(x))
    
    
def md2σ(x):
    return mσ(x) * (1. - mσ(x)) * (1. - 2.*mσ(x))

In [5]:
x = tf.random.uniform((10,4))
W = tf.random.uniform((4,1))
b = tf.random.uniform((1,1))
z = x @ W + b
print(z.shape)
print(mdσ(z).shape)

(10, 1)
(10, 1)


In [6]:
x = [[10.], [20.], [30.]]

print(mσ(x))
print(tf.keras.activations.sigmoid(x))
print(mdσ(x))
print(md2σ(x))

tf.Tensor(
[[0.9999546]
 [1.       ]
 [1.       ]], shape=(3, 1), dtype=float32)
tf.Tensor(
[[0.9999546]
 [1.       ]
 [1.       ]], shape=(3, 1), dtype=float32)
tf.Tensor(
[[4.5416677e-05]
 [0.0000000e+00]
 [0.0000000e+00]], shape=(3, 1), dtype=float32)
tf.Tensor(
[[-4.541255e-05]
 [-0.000000e+00]
 [-0.000000e+00]], shape=(3, 1), dtype=float32)


Does not exactly match the results/values in Julia.

Define Neural Network.

In [7]:
# Define model architecture
class PINN(tf.keras.Model):
    """ Set basic architecture of the PINN model."""

    def __init__(self,
                 output_dim=1,
                 num_hidden_layers=3,
                 num_neurons_per_layer=20,
                 activationfunction = 'sigmoid',
                 kernel_initializer='glorot_normal',
                 **kwargs):
        
        super().__init__(**kwargs)

        self.num_hidden_layers = num_hidden_layers
        self.input_dim = 2
        self.output_dim = output_dim

        # Define NN architecture
        
        # Inititialize num_hidden_layers many fully connected dense layers
        self.hidden = [tf.keras.layers.Dense(num_neurons_per_layer,
                                             activation = activationfunction,
                                             kernel_initializer=kernel_initializer) for _ in range(self.num_hidden_layers)]
        
        # Output layer
        #self.out = tf.keras.layers.Dense(output_dim, activation=None)
        self.out = tf.keras.layers.Dense(output_dim, activation = activationfunction)
        
    def call(self, X):
        """Forward-pass through neural network."""
        self.tmp_layer_output = [X]
        #Z = self.scale(X)
        Z = X
        
        for i in range(self.num_hidden_layers):
            Z = self.hidden[i](Z)
            self.tmp_layer_output.append(Z)
            
        return self.out(Z)
    
    def get_gradient(self, x):
        output = self.call(x)
        δ = get_gradient_layer(self.out.weights[0], self.out.weights[1], self.tmp_layer_output[-1], np.identity(self.output_dim))

        for k in range(self.num_hidden_layers-1, -1, -1):
            δ = get_gradient_layer(self.hidden[k].weights[0], self.hidden[k].weights[1], self.tmp_layer_output[k], δ)

        return output, δ
    

    def get_gradient_and_hessian(self, x):
        #x = tf.reshape(x, (1,2))
        output = self.call(x)
        δ,ϑ,z = get_gradient_hessian_last_layer(self.out.weights[0], self.out.weights[1], self.tmp_layer_output[-1], np.identity(self.output_dim))

        for k in range(self.num_hidden_layers-1, -1, -1):
            δ,ϑ = get_gradient_hessian_hidden_layer(self.hidden[k].weights[0], self.hidden[k].weights[1], self.tmp_layer_output[k], δ,  ϑ)

        return output, δ, ϑ

Compute gradient.

Compute gradient for layer l.

In [8]:
def get_gradient_layer(W,b,a,δ):
#     z1 = tf.transpose(a @ W + b)  
#     b = tf.reshape(b, z1.shape)
#     z2 = z1 + b
#     z3 = mdσ(z1) * δ
    return W @ (mdσ(tf.transpose(a @ W + b)) * δ)

Compute gradient of neural network.

In [9]:
# def get_gradient(N, x):
#     output = N(x)
#     δ = get_gradient_layer(N.out.weights[0], N.out.weights[1], N.tmp_layer_output[-1], 1.)

#     for k in range(N.num_hidden_layers-1, -1, -1):
#         δ = get_gradient_layer(N.hidden[k].weights[0], N.hidden[k].weights[1], N.tmp_layer_output[k], δ)
            
#     return output, δ

In [10]:
def tensor_hadamard(v,A):
    return [tf.reshape(i, (i.shape[0], 1)) * A for i in tf.unstack(v, axis = 1)]

Compute gradient and Hessian of last layer.

In [11]:
def get_gradient_hessian_last_layer(W,b,a,δ):
#     z1 = tf.transpose(a @ W)  
#     b = tf.reshape(b, z1.shape)
#     z2 = z1 + b
#     z3 = mdσ(z2) * δ
#     ϑ = tf.linalg.diag(tf.reshape(md2σ(z2), [-1]))''

#     z = tf.transpose(a @ W + b)
#     return W @ (mdσ(z) * δ), W @ (md2σ(z) * tf.transpose(W))
    
    z = tf.transpose(a @ W + b)
    return W @ (mdσ(z) * δ), W @ tensor_hadamard(δ * md2σ(z),tf.transpose(W)), z
#[tf.reshape(i, (i.shape[0], 1)) * tf.transpose(W) for i in tf.unstack(δ * md2σ(z), axis = 1)], z

Compute gradient and Hessian of hidden layer.

In [12]:
def get_gradient_hessian_hidden_layer(W,b,a,δ,ϑ):
#     z1 = tf.transpose(a @ W)  
#     b = tf.reshape(b, np.shape(z1))
#     z2 = z1 + b
#     z3 = mdσ(z2) * δ
#     t2 = δ * md2σ(z2)
#     H1 = W @ tf.linalg.diag(tf.reshape(t2, [-1])) @ tf.transpose(W)
#     dσt = tf.linalg.diag(tf.reshape(mdσ(z2), [-1]))
#     H2 = W @ dσt @ ϑ @ dσt @ tf.transpose(W)

#     z = tf.transpose(a @ W + b)
#     dσt = mdσ(z) * tf.transpose(W)
#     return W @ (mdσ(z) * δ), W @ ((δ * md2σ(z)) * tf.transpose(W)) + tf.transpose(dσt) @ ϑ @ dσt 

    z = tf.transpose(a @ W + b)
    WT = tf.transpose(W)
    mdσz = mdσ(z)
    dσt = tensor_hadamard(mdσz, WT)
    dσtT = tf.transpose(dσt, perm=[0, 2, 1])
    t2 = tensor_hadamard(δ * md2σ(z), WT)
    return W @ (mdσz * δ), W @ t2 + dσtT @ ϑ @ dσt 

Compute Hessian and gradient of neural network.

In [13]:
# def get_hessian(N, x):
#     #x = tf.reshape(x, (1,2))
#     output = N(x)
#     δ,ϑ = get_gradient_hessian_last_layer(N.out.weights[0], N.out.weights[1], N.tmp_layer_output[-1], 1.)

#     for k in range(N.num_hidden_layers-1, -1, -1):
#         δ,ϑ = get_gradient_hessian_hidden_layer(N.hidden[k].weights[0], N.hidden[k].weights[1], N.tmp_layer_output[k], δ,  ϑ)
      
    
#     return output, δ, ϑ

In [14]:
# x = tf.random.normal((20,))
# A = tf.random.normal((20,4))
# print(x)
# print(A)
# print(tf.math.multiply(A,x))
# print(tf.math.multiply(x,A))
# print(A)
# M = tf.tensordot(x, A, axes=0)
# print(M)
# B = tf.random.normal((3,3))
# print(B @ M)
# print(M@M)
#tf.reshape(x, [-1])
#tf.tensordot(tf.transpose(x), A, axes=1)
#[x[:,i] * A for i in range(x.shape[0])]
# for i in tf.unstack(x, axis = 1):
#     print(i*A)
# B = tf.random.normal((3,20,20))
# C = tf.random.normal((3,20,20))
# B@C
# print(tf.reshape([i * A for i in tf.unstack(x, axis = 1)], (3,20,20)))
# print(tf.transpose(tf.reshape([i * A for i in tf.unstack(x, axis = 1)], (3,20,20))))
#print(A)

#print(tf.reshape([tf.transpose(i) for i in tf.unstack(A, axis = 0)], (3,4,4)))

#tf.reshape(x, (x.shape[0], 1))*A

Why do we get a 2D vector when we insert a 2D vector?

In [15]:
NeuralN = PINN()

x = tf.random.normal((10,2))

#out = NeuralN(x)
#print(out)

out1, δ1 = NeuralN.get_gradient(x)
out2, δ2, ϑ = NeuralN.get_gradient_and_hessian(x)

print(δ1- δ2)
print(δ1)
#print(tf.reshape(ϑ, [-1]))

tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]], shape=(2, 10), dtype=float32)
tf.Tensor(
[[-1.1629434e-03 -1.1721451e-03 -1.1019403e-03 -1.2002669e-03
  -1.0989591e-03 -1.1910177e-03 -1.1870349e-03 -1.1253051e-03
  -1.0930389e-03 -1.1791835e-03]
 [ 2.1174898e-04  2.2755483e-04  2.2179197e-04  2.3000706e-04
   2.1788178e-04  2.3825876e-04  1.8178142e-04  8.4744795e-05
   1.8635154e-04  2.2060158e-04]], shape=(2, 10), dtype=float32)


-> We need to choose appropriate dtypes so that no operation overflows.

In [16]:
# def _fvals1(N, x):

#     with tf.GradientTape() as g:
#         g.watch(x)
#         y = N(x)

#     dy_dx = g.gradient(y, x)
#     dy_dx = np.transpose(dy_dx.numpy())

#     return y, dy_dx

def _fvals1(N, t, x):

    with tf.GradientTape(persistent=True) as tape:
        tape.watch(t)
        tape.watch(x)
        tx = tf.stack([t, x], axis=1)
        y = N(tx)
                
    yt = tape.gradient(y, t)
    yx = tape.gradient(y, x)

    return y, yt, yx

In [17]:

for i in range(10):
    x = tf.random.uniform((1,2))
    NeuralN = PINN()
    out1, δ1 = NeuralN.get_gradient(x)
    out2, δ2, ϑ = NeuralN.get_gradient_and_hessian(x)
    out_ad, yt_ad, yx_ad = _fvals1(NeuralN, x[:,0], x[:,1])
    print(np.linalg.norm(δ1[1]-yx_ad))
    print(np.linalg.norm(δ1[0]-yt_ad))
    print(np.linalg.norm(δ2[1]-yx_ad))
    print(np.linalg.norm(δ2[0]-yt_ad))

4.656613e-10
4.656613e-10
4.656613e-10
4.656613e-10
1.1641532e-10
2.3283064e-10
1.1641532e-10
2.3283064e-10
4.656613e-10
1.1641532e-10
4.656613e-10
1.1641532e-10
0.0
5.820766e-11
0.0
5.820766e-11
5.2386895e-10
3.4924597e-10
5.2386895e-10
3.4924597e-10
2.3283064e-10
2.3283064e-10
2.3283064e-10
2.3283064e-10
5.820766e-11
1.1641532e-10
5.820766e-11
1.1641532e-10
5.820766e-11
0.0
5.820766e-11
0.0
5.820766e-11
0.0
5.820766e-11
0.0
0.0
0.0
0.0
0.0


In [18]:
# def _fvals2(N, x):

#     with tf.GradientTape(persistent=True) as h:
#         h.watch(x)
#         with tf.GradientTape() as g:
#             g.watch(x)
#             y = N(x)

#         dy_dx = g.gradient(y, x)
    
#     d2y_d2x = h.jacobian(dy_dx, x)

#     return y, dy_dx, d2y_d2x

def _fvals2_ad(N, t, x):
    
    with tf.GradientTape(persistent=True) as tape:
        tape.watch(t)
        tape.watch(x)
        tx = tf.stack([t, x], axis=1)
        y = N(tx)
        yx = tape.gradient(y, x)
    
    yt = tape.gradient(y, t)
    yxx = tape.gradient(yx, x)

    return y, yt, yx, yxx

In [19]:
for i in range(20):
    x = tf.random.normal((1,2))
    NeuralN = PINN()
    out,δ,ϑ = NeuralN.get_gradient_and_hessian(x)
    out_ad, yx_ad, yt_ad, yxx_ad = _fvals2_ad(NeuralN, x[:,0], x[:,1])
    print(np.linalg.norm(ϑ[0, 1, 1]-yxx_ad))

5.820766e-11
1.4551915e-11
1.4551915e-11
7.275958e-12
7.275958e-12
1.4551915e-11
3.637979e-12
7.2759576e-11
0.0
2.910383e-11
0.0
1.546141e-11
1.4551915e-11
5.0931703e-11
2.910383e-11
7.275958e-12
3.6379788e-11
2.910383e-11
1.4551915e-11
3.6379788e-11


In [22]:
NeuralN = PINN()

x = tf.random.normal((100,2))

out2, δ2, ϑ = NeuralN.get_gradient_and_hessian(x)
out_ad, yx_ad, yt_ad, yxx_ad = _fvals2_ad(NeuralN, x[:,0], x[:,1])

# print(yxx_ad)
# print(ϑ[:, 1, 1])
# print(δ2[0,:])
# print(δ2[1,:])
#print(tf.linalg.norm(yxx_ad - ϑ[:, 1, 1]))
print(out2.shape)

(100, 1)


Maybe gradient tape thinks that the neural network is not differentiable?

# Explicit derivatives of ResNet

Here we only approximate the "half" gradient so far. 

In [24]:
class PINN_ResNet(tf.keras.Model):
    """ Set basic architecture of the PINN model."""

    def __init__(self,
                 ResNetLayers=2,
                 ResNetNeurons=16,
                 ResNetStepsize=1.0,
                 ResNetActivation='sigmoid',
                 **kwargs):
        
        super(PINN_ResNet, self).__init__(**kwargs)
        
        #RNact = tf.keras.activations.get(ResNetActivation)
        #RNact = my_act
        RNact = ResNetActivation
        

        
        self.ResNetLayers = ResNetLayers
        self.ResNetStepsize = ResNetStepsize

        self.ResNet = [tf.keras.layers.Dense(ResNetNeurons,
                                        activation = RNact) for _ in range(self.ResNetLayers)]
        self.wb = tf.keras.layers.Dense(1)
        self.A = tf.keras.layers.Dense(2, use_bias=False)
        self.c = tf.keras.layers.Dense(1, use_bias=False)
        
        #self.num_hidden_layers = num_hidden_layers
        self.input_dim = 2
        self.output_dim = 1


        # Define NN architecture
        
        # Output layer
        #self.out = tf.keras.layers.Dense(1, activation='sigmoid')

        
    def call(self, input_tensor, training=False):
        """Forward-pass through neural network."""
        
        self.tmp_layer_output = [input_tensor]
        
        N = self.ResNet[0](input_tensor, training=training)
        
        for i in range(1, self.ResNetLayers):
            self.tmp_layer_output.append(N)
            N = N + self.ResNetStepsize * self.ResNet[i](N, training=training)
        
        Phi = self.wb(N, training=training)

        As = self.A(input_tensor, training=training)
        sAs = tf.keras.layers.Dot(axes=(1))([input_tensor, As])
        Phi += .5 * sAs
        Phi += self.c(input_tensor, training=training)
            
        return Phi
    
    def get_gradient(self, x):
        output = self.call(x)
        δ = get_gradient_layer(self.ResNet[-1].weights[0], self.ResNet[-1].weights[1], self.tmp_layer_output[-1], self.wb.weights[0])
        
        δ = self.wb.weights[0] + self.ResNetStepsize * δ

        for k in range(self.ResNetLayers-2, 0, -1):
            δ = δ + self.ResNetStepsize * get_gradient_layer(self.ResNet[k].weights[0], self.ResNet[k].weights[1], self.tmp_layer_output[k], δ)


        δ = get_gradient_layer(self.ResNet[0].weights[0], self.ResNet[0].weights[1], self.tmp_layer_output[0], δ)

        M = self.A.weights[0]

        return output, δ + 0.5*tf.transpose(x @ (M + tf.transpose(M))) + self.c.weights[0]
        
        
#     def get_gradient_and_hessian(self, x):
#         x = tf.reshape(x, (1,2))
#         output = self.call(x)
#         δ,ϑ,z = get_gradient_hessian_layer_ResNet(self.ResNet[-1].weights[0], self.ResNet[-1].weights[1], self.tmp_layer_output[-1], self.wb.weights[0])

#         δ = self.wb.weights[0] + self.ResNetStepsize * δ

#         for k in range(self.ResNetLayers-2, 0, -1):
#             δ_new, ϑ_new_1, z = get_gradient_hessian_layer_ResNet(self.ResNet[k].weights[0], self.ResNet[k].weights[1], self.tmp_layer_output[k], δ)
#             t = ϑ + self.ResNetStepsize * self.ResNet[k].weights[0] @ ( mdσ(z) * ϑ)
#             ϑ_new_2 = tf.transpose(t) + self.ResNetStepsize * self.ResNet[k].weights[0] @ ( mdσ(z) * tf.transpose(t))
#             ϑ = ϑ_new_1 + ϑ_new_2
#             δ = δ + self.ResNetStepsize * δ_new


#         δ, ϑ = get_gradient_hessian_hidden_layer(self.ResNet[0].weights[0], self.ResNet[0].weights[1], self.tmp_layer_output[0], δ, ϑ)

#         M = self.A.weights[0]

#         return output, δ + 0.5*tf.transpose(x @ (M + tf.transpose(M))) + self.c.weights[0], ϑ + 0.5*(M + tf.transpose(M))

    def get_gradient_and_hessian(self, x):
        output = self.call(x)
        δ,ϑ,z = get_gradient_hessian_last_layer(self.ResNet[-1].weights[0], self.ResNet[-1].weights[1], self.tmp_layer_output[-1], self.wb.weights[0])

        δ = self.wb.weights[0] + self.ResNetStepsize * δ

        for k in range(self.ResNetLayers-2, 0, -1):
            δ_new, ϑ_new_1, z = get_gradient_hessian_last_layer(self.ResNet[k].weights[0], self.ResNet[k].weights[1], self.tmp_layer_output[k], δ)
            mz = mdσ(z)
            #t = ϑ + self.ResNetStepsize * self.ResNet[k].weights[0] @ tf.reshape([tf.reshape(i, (i.shape[0], 1)) * ϑ for i in tf.unstack(mz, axis = 1)], (mz.shape[1],ϑ.shape[0],ϑ.shape[1]))
            t = ϑ + self.ResNetStepsize * self.ResNet[k].weights[0] @ tensor_hadamard(mz, ϑ)
            #tT = tf.reshape([tf.transpose(i) for i in tf.unstack(t, axis = 0)], (t.shape[0],t.shape[2],t.shape[1]))
            tT = tf.transpose(t, perm=[0, 2, 1])
            #ϑ_new_2 = tT + self.ResNetStepsize * self.ResNet[k].weights[0] @ tf.reshape([tf.reshape(i, (i.shape[0], 1)) * tT for i in tf.unstack(mz, axis = 1)], (mz.shape[1],tT.shape[0],tT.shape[1]))
            ϑ_new_2 = tT + self.ResNetStepsize * self.ResNet[k].weights[0] @ tensor_hadamard(mz, tT)
            ϑ = ϑ_new_1 + ϑ_new_2
            δ = δ + self.ResNetStepsize * δ_new


        δ, ϑ = get_gradient_hessian_hidden_layer(self.ResNet[0].weights[0], self.ResNet[0].weights[1], self.tmp_layer_output[0], δ, ϑ)

        M = self.A.weights[0]

        return output, δ + 0.5*tf.transpose(x @ (M + tf.transpose(M))) + self.c.weights[0], ϑ + 0.5*(M + tf.transpose(M))

Gradient of model, which approximates solution of pde

In [25]:
# def get_gradient_ResNet(R,x):
#     output = R(x)
#     δ = get_gradient_layer(R.ResNet[-1].weights[0], R.ResNet[-1].weights[1], R.tmp_layer_output[-1], R.wb.weights[0])

#     δ = R.wb.weights[0] + R.ResNetStepsize * δ
 
#     for k in range(R.ResNetLayers-2, 0, -1):
#         δ = δ + R.ResNetStepsize * get_gradient_layer(R.ResNet[k].weights[0], R.ResNet[k].weights[1], R.tmp_layer_output[k], δ)
          
    
#     δ = get_gradient_layer(R.ResNet[0].weights[0], R.ResNet[0].weights[1], R.tmp_layer_output[0], δ)
    
#     M = R.A.weights[0]
    
#     return output, δ + 0.5*tf.transpose(x @ (M + tf.transpose(M))) + R.c.weights[0]

Something is wrong with the 'whole' gradient?

In [26]:
Resnet = PINN_ResNet()

x = tf.constant([[1., 10.]])

out, δ = Resnet.get_gradient(x)

print(δ)

out_ad, yx_ad, yt_ad = _fvals1(Resnet, x[:,0], x[:,1])

print(yx_ad)
print(yt_ad)

print(np.linalg.norm(δ[0] - yx_ad))

tf.Tensor(
[[ 6.383861  ]
 [-0.06816453]], shape=(2, 1), dtype=float32)
tf.Tensor([6.383861], shape=(1,), dtype=float32)
tf.Tensor([-0.0681645], shape=(1,), dtype=float32)
0.0


In [27]:
for i in range(10):
    x = tf.random.normal((1,2))
    Resnet = PINN_ResNet()
    out, δ = Resnet.get_gradient(x)
    out_ad, yx_ad, yt_ad = _fvals1(Resnet, x[:,0], x[:,1])
    print(np.linalg.norm(δ[0] - yx_ad))
    print(np.linalg.norm(δ[1] - yt_ad))

0.0
1.1920929e-07
0.0
2.2351742e-08
2.9802322e-08
1.1920929e-07
1.1920929e-07
1.1920929e-07
0.0
1.1920929e-07
4.4703484e-08
0.0
0.0
5.9604645e-08
1.1920929e-07
0.0
0.0
5.9604645e-08
5.9604645e-08
0.0


In [28]:
x = tf.random.normal((19,2))
Resnet = PINN_ResNet()
out, δ = Resnet.get_gradient(x)
out_ad, yx_ad, yt_ad = _fvals1(Resnet, x[:,0], x[:,1])
print(np.linalg.norm(δ[0,:]-yx_ad))
print(np.linalg.norm(δ[1,:]-yt_ad))

3.1610136e-07
4.3546078e-07


In [29]:
def get_gradient_hessian_layer_ResNet(W,b,a,δ):
#     z1 = np.transpose(a @ W)  
#     b = np.reshape(b, np.shape(z1))
#     z2 = z1 + b
#     z3 = np.diag(tf.reshape(mdσ(z2), [-1])) @ δ
    
#     z4 = md2σ(z2) * δ
#     ϑ = np.diag(tf.reshape(z4, [-1]))
    
#     return W @ z3, W @ ϑ @ np.transpose(W)
    z = tf.transpose(a @ W + b)
    return W @ (mdσ(z) * δ), W @ ((md2σ(z) * δ) * tf.transpose(W)), z

In [30]:
# def get_hessian_ResNet(R,x):
#     x = tf.reshape(x, (1,2))
#     output = R(x)
#     δ,ϑ,z = get_gradient_hessian_layer_ResNet(R.ResNet[-1].weights[0], R.ResNet[-1].weights[1], R.tmp_layer_output[-1], R.wb.weights[0])

#     δ = R.wb.weights[0] + R.ResNetStepsize * δ
 
#     for k in range(R.ResNetLayers-2, 0, -1):
#         δ_new, ϑ_new_1, z = get_gradient_hessian_layer_ResNet(R.ResNet[k].weights[0], R.ResNet[k].weights[1], R.tmp_layer_output[k], δ)
#         t = ϑ + R.ResNetStepsize * R.ResNet[k].weights[0] @ ( mdσ(z) * ϑ)
#         ϑ_new_2 = tf.transpose(t) + R.ResNetStepsize * R.ResNet[k].weights[0] @ ( mdσ(z) * tf.transpose(t))
#         ϑ = ϑ_new_1 + ϑ_new_2
#         δ = δ + R.ResNetStepsize * δ_new
    
      
#     δ, ϑ = get_gradient_hessian_hidden_layer(R.ResNet[0].weights[0], R.ResNet[0].weights[1], R.tmp_layer_output[0], δ, ϑ)
    
#     M = R.A.weights[0]
    
#     return output, δ + 0.5*tf.transpose(x @ (M + tf.transpose(M))) + R.c.weights[0], ϑ + 0.5*(M + tf.transpose(M))

In [31]:
tf.random.set_seed(0)
for i in range(10):
    x = tf.random.normal((1,2))
    Resnet = PINN_ResNet()
    out, δ, ϑ = Resnet.get_gradient_and_hessian(x)
    out_ad, yx_ad, yt_ad, yxx_ad = _fvals2_ad(Resnet, x[:,0], x[:,1])
    #print(np.linalg.norm(ϑ[1,1]-yxx_ad))
    print(tf.linalg.norm(ϑ[:,1,1] - yxx_ad))

tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(1.4901161e-08, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)


In [36]:
x = tf.random.normal((100,2))
Resnet = PINN_ResNet()
out2, δ2, ϑ = Resnet.get_gradient_and_hessian(x)
out, yx_ad, yt_ad, yxx_ad = _fvals2_ad(Resnet, x[:,0], x[:,1])
# print(result[2][:,0,0])
# print(yxx_ad)
#print(np.linalg.norm(result[2][:,1,1] - yxx_ad))
# print(tf.reshape(result[1][:,0], [-1]))
# print(tf.concat(yt_ad, 0))
# print(np.linalg.norm(tf.reshape(result[1][:,1], [-1]) - tf.concat(yt_ad, 0)))
# print(np.linalg.norm(tf.reshape(result[1][:,0], [-1]) - tf.concat(yx_ad, 0)))
print(tf.linalg.norm(yxx_ad - ϑ[:, 1, 1]))

tf.Tensor(3.573173e-08, shape=(), dtype=float32)
