# First and second derivative of FNN with respect to input (tensorflow)

Import necessary packages.

In [1]:
import tensorflow as tf
import numpy as np

Define activation function and its derivatives.

In [2]:
# Custom activation function
# from keras.layers import Activation
# from keras import backend as K
# from keras.utils.generic_utils import get_custom_objects

#def mσ(x):
    #return np.abs(x) + np.log(1. + np.exp(-2. * np.abs(x)))
    
def mσ(x):
    return tf.math.divide(1, 1 + tf.math.exp(tf.math.negative(x)))

# get_custom_objects().update({'custom_activation': Activation(mσ)})


In [3]:
#def mdσ(x):
    #return np.tanh(x)
    
    
#def md2σ(x):
    #return np.divide(1., np.square(np.cosh(x)))

def mdσ(x):
    return mσ(x) * (1 - mσ(x))
    
    
def md2σ(x):
    return mσ(x) * (1 - mσ(x)) * (1 - 2*mσ(x))

In [4]:
x = [[10.], [20.], [30.]]

print(mσ(x))
print(tf.keras.activations.sigmoid(x))
print(mdσ(x))
print(md2σ(x))

tf.Tensor(
[[0.9999546]
 [1.       ]
 [1.       ]], shape=(3, 1), dtype=float32)
tf.Tensor(
[[0.9999546]
 [1.       ]
 [1.       ]], shape=(3, 1), dtype=float32)
tf.Tensor(
[[4.5416677e-05]
 [0.0000000e+00]
 [0.0000000e+00]], shape=(3, 1), dtype=float32)
tf.Tensor(
[[-4.541255e-05]
 [-0.000000e+00]
 [-0.000000e+00]], shape=(3, 1), dtype=float32)


Does not exactly match the results/values in Julia.

Define Neural Network.

In [22]:
# Define model architecture
class PINN(tf.keras.Model):
    """ Set basic architecture of the PINN model."""

    def __init__(self,
                 output_dim=1,
                 num_hidden_layers=3,
                 num_neurons_per_layer=20,
                 activationfunction = 'sigmoid',
                 kernel_initializer='glorot_normal',
                 **kwargs):
        
        super().__init__(**kwargs)

        self.num_hidden_layers = num_hidden_layers
        self.input_dim = 2
        self.output_dim = output_dim

        # Define NN architecture
        
        # Inititialize num_hidden_layers many fully connected dense layers
        self.hidden = [tf.keras.layers.Dense(num_neurons_per_layer,
                                             activation = activationfunction,
                                             kernel_initializer=kernel_initializer) for _ in range(self.num_hidden_layers)]
        
        # Output layer
        #self.out = tf.keras.layers.Dense(output_dim, activation=None)
        self.out = tf.keras.layers.Dense(output_dim, activation = activationfunction)
        
    def call(self, X):
        """Forward-pass through neural network."""
        self.tmp_layer_output = [X]
        #Z = self.scale(X)
        Z = X
        
        for i in range(self.num_hidden_layers):
            Z = self.hidden[i](Z)
            self.tmp_layer_output.append(Z)
            
        return self.out(Z)

Compute gradient.

Compute gradient for layer l.

In [23]:
def get_gradient_layer(W,b,a,δ):
#     z1 = tf.transpose(a @ W + b)  
#     b = tf.reshape(b, z1.shape)
#     z2 = z1 + b
#     z3 = mdσ(z1) * δ
    return W @ (mdσ(tf.transpose(a @ W + b)) * δ)

Compute gradient of neural network.

In [24]:
def get_gradient(N, x):
    output = N(x)
    δ = get_gradient_layer(N.out.weights[0], N.out.weights[1], N.tmp_layer_output[-1], np.identity(N.output_dim))

    for k in range(N.num_hidden_layers-1, -1, -1):
        δ = get_gradient_layer(N.hidden[k].weights[0], N.hidden[k].weights[1], N.tmp_layer_output[k], δ)
            
    return output, δ

Compute gradient and Hessian of last layer.

In [25]:
def get_gradient_hessian_last_layer(W,b,a,δ):
#     z1 = tf.transpose(a @ W)  
#     b = tf.reshape(b, z1.shape)
#     z2 = z1 + b
#     z3 = mdσ(z2) * δ
    
#     ϑ = tf.linalg.diag(tf.reshape(md2σ(z2), [-1]))
    z = tf.transpose(a @ W + b)
    return W @ (mdσ(z) * δ), W @ (md2σ(z) * tf.transpose(W))

Compute gradient and Hessian of hidden layer.

In [26]:
def get_gradient_hessian_hidden_layer(W,b,a,δ,ϑ):
#     z1 = tf.transpose(a @ W)  
#     b = tf.reshape(b, np.shape(z1))
#     z2 = z1 + b
#     z3 = mdσ(z2) * δ
    
#     t2 = δ * md2σ(z2)
#     H1 = W @ tf.linalg.diag(tf.reshape(t2, [-1])) @ tf.transpose(W)

#     dσt = tf.linalg.diag(tf.reshape(mdσ(z2), [-1]))
#     H2 = W @ dσt @ ϑ @ dσt @ tf.transpose(W)
    z = tf.transpose(a @ W + b)
    dσt = mdσ(z) * tf.transpose(W)
    return W @ (mdσ(z) * δ), W @ ((δ * md2σ(z)) * tf.transpose(W)) + tf.transpose(dσt) @ ϑ @ dσt 

Compute Hessian and gradient of neural network.

In [27]:
def get_hessian(N, x):
    output = N(x)
    δ,ϑ = get_gradient_hessian_last_layer(N.out.weights[0], N.out.weights[1], N.tmp_layer_output[-1], np.identity(N.output_dim))

    for k in range(N.num_hidden_layers-1, -1, -1):
        δ,ϑ = get_gradient_hessian_hidden_layer(N.hidden[k].weights[0], N.hidden[k].weights[1], N.tmp_layer_output[k], δ,  ϑ)
      
    
    return output, δ, ϑ

In [28]:
NeuralN = PINN()

x = tf.random.normal((3,2))

out2, δ2, ϑ = get_hessian(NeuralN,x)

InvalidArgumentError: Incompatible shapes: [1,3] vs. [1,20] [Op:Mul]

In [29]:
x = tf.random.normal((9,2))
NeuralN(x)
A = tf.random.normal((1,20))
len(NeuralN.tmp_layer_output)
#print(NeuralN.tmp_layer_output[3])
z = NeuralN.tmp_layer_output[3] @ NeuralN.out.weights[0] + NeuralN.out.weights[1]
print(z)
print(md2σ(z))

tf.Tensor(
[[0.6343183 ]
 [0.64075255]
 [0.64088327]
 [0.6389887 ]
 [0.6329725 ]
 [0.6389991 ]
 [0.6345287 ]
 [0.6402453 ]
 [0.63730335]], shape=(9, 1), dtype=float32)
tf.Tensor(
[[-0.06950492]
 [-0.07002504]
 [-0.07003557]
 [-0.06988294]
 [-0.06939548]
 [-0.06988379]
 [-0.06952199]
 [-0.06998423]
 [-0.06974681]], shape=(9, 1), dtype=float32)


Why do we get a 2D vector when we insert a 2D vector?

In [30]:
NeuralN = PINN()

x = tf.random.normal((1,2))

#out = NeuralN(x)
#print(out)

out1, δ1 = get_gradient(NeuralN, x)
out2, δ2, ϑ = get_hessian(NeuralN,x)

print(δ1- δ2)
print(δ1)
#print(tf.reshape(ϑ, [-1]))

tf.Tensor(
[[0.]
 [0.]], shape=(2, 1), dtype=float32)
tf.Tensor(
[[-0.00080858]
 [-0.00197051]], shape=(2, 1), dtype=float32)


In [31]:
x = tf.random.normal((20,2))
out1, δ1 = get_gradient(NeuralN, x)
print(δ1)
print(out1)
# δ_ad = _fvals1(NeuralN, x)[1]
# print(δ_ad[0,:])

tf.Tensor(
[[-0.00070658 -0.00079013 -0.0010271  -0.00075858 -0.00110465 -0.00053696
  -0.00092481 -0.00093667 -0.00097688 -0.00121836 -0.00090906 -0.00078221
  -0.00093113 -0.00091588 -0.00087855 -0.00095143 -0.00097521 -0.00100542
  -0.00052011 -0.00102276]
 [-0.00204806 -0.00201798 -0.00188646 -0.00205364 -0.0016125  -0.00198362
  -0.00208349 -0.00204013 -0.00199662 -0.00124641 -0.0021085  -0.00203214
  -0.00199849 -0.00210094 -0.00197305 -0.00197617 -0.00190486 -0.00190325
  -0.00198162 -0.00176661]], shape=(2, 20), dtype=float32)
tf.Tensor(
[[0.6271702 ]
 [0.62928355]
 [0.63170743]
 [0.62668353]
 [0.6339369 ]
 [0.62686026]
 [0.63075143]
 [0.627758  ]
 [0.6308036 ]
 [0.63538605]
 [0.62895566]
 [0.6283434 ]
 [0.6278    ]
 [0.6292336 ]
 [0.6295661 ]
 [0.63207185]
 [0.63071954]
 [0.6322825 ]
 [0.62673134]
 [0.63136965]], shape=(20, 1), dtype=float32)


-> We need to choose appropriate dtypes so that no operation overflows.

In [32]:
def _fvals1(N, x):

    with tf.GradientTape() as g:
        g.watch(x)
        y = N(x)

    dy_dx = g.gradient(y, x)
    dy_dx = np.transpose(dy_dx.numpy())

    return y, dy_dx

In [33]:
for i in range(10):
    x = tf.random.normal((1,2))
    NeuralN = PINN()
    out = NeuralN(x)
    out1, δ1 = get_gradient(NeuralN, x)
    out2, δ2,ϑ = get_hessian(NeuralN, x)
    δ_ad = _fvals1(NeuralN, x)[1]
    print(np.linalg.norm(δ1-δ2))
    print(np.linalg.norm(δ1-δ_ad))
    print(np.linalg.norm(δ2-δ_ad))

0.0
0.0
0.0
0.0
2.7456498e-10
2.7456498e-10
0.0
1.7522826e-10
1.7522826e-10
0.0
2.3283064e-10
2.3283064e-10
0.0
6.5078144e-11
6.5078144e-11
0.0
5.9999083e-10
5.9999083e-10
0.0
2.098707e-10
2.098707e-10
0.0
4.197414e-10
4.197414e-10
0.0
1.1641532e-10
1.1641532e-10
0.0
1.7462298e-10
1.7462298e-10


In [34]:
def _fvals2(N, x):

    with tf.GradientTape(persistent=True) as h:
        h.watch(x)
        with tf.GradientTape() as g:
            g.watch(x)
            y = N(x)

        dy_dx = g.gradient(y, x)
    
    d2y_d2x = h.jacobian(dy_dx, x)

    return y, dy_dx, d2y_d2x

In [35]:
for i in range(10):
    x = tf.random.normal((1,2))
    NeuralN = PINN()
    out,δ,ϑ = get_hessian(NeuralN,x)
    ϑ_ad = _fvals2(NeuralN, x)[2]
    print(np.linalg.norm(ϑ-ϑ_ad))

0.00022504566
0.0005382768
0.00043916347
7.4847296e-05
0.0003831832
9.887671e-05
0.0004874908
8.740402e-05
8.402206e-05
0.00029596154


Maybe gradient tape thinks that the neural network is not differentiable?

# Explicit derivatives of ResNet

Here we only approximate the "half" gradient so far. 

In [18]:
class PINN_ResNet(tf.keras.Model):
    """ Set basic architecture of the PINN model."""

    def __init__(self,
                 ResNetLayers=2,
                 ResNetNeurons=16,
                 ResNetStepsize=1.0,
                 ResNetActivation='sigmoid',
                 **kwargs):
        
        super(PINN_ResNet, self).__init__(**kwargs)
        
        #RNact = tf.keras.activations.get(ResNetActivation)
        #RNact = my_act
        RNact = ResNetActivation
        

        
        self.ResNetLayers = ResNetLayers
        self.ResNetStepsize = ResNetStepsize

        self.ResNet = [tf.keras.layers.Dense(ResNetNeurons,
                                        activation = RNact) for _ in range(self.ResNetLayers)]
        self.wb = tf.keras.layers.Dense(1)
        self.A = tf.keras.layers.Dense(2, use_bias=False)
        self.c = tf.keras.layers.Dense(1, use_bias=False)
        
        #self.num_hidden_layers = num_hidden_layers
        self.input_dim = 2
        self.output_dim = 1


        # Define NN architecture
        
        # Output layer
        #self.out = tf.keras.layers.Dense(1, activation='sigmoid')

        
    def call(self, input_tensor, training=False):
        """Forward-pass through neural network."""
        
        self.tmp_layer_output = [input_tensor]
        
        N = self.ResNet[0](input_tensor, training=training)
        
        for i in range(1, self.ResNetLayers):
            self.tmp_layer_output.append(N)
            N = N + self.ResNetStepsize * self.ResNet[i](N, training=training)
        
        Phi = self.wb(N, training=training)

#         As = self.A(input_tensor, training=training)
#         sAs = tf.keras.layers.Dot(axes=(1))([input_tensor, As])
#         Phi += .5 * sAs
#         Phi += self.c(input_tensor, training=training)
            
        return Phi

Gradient of model, which approximates solution of pde

In [19]:
def get_gradient_ResNet(R):
    δ = get_gradient_layer(R.ResNet[-1].weights[0], R.ResNet[-1].weights[1], R.tmp_layer_output[-1], R.wb.weights[0])

    δ = R.wb.weights[0] + R.ResNetStepsize * δ
 
    for k in range(R.ResNetLayers-2, 0, -1):
        δ = δ + R.ResNetStepsize * get_gradient_layer(R.ResNet[k].weights[0], R.ResNet[k].weights[1], R.tmp_layer_output[k], δ)
          
    
    δ = get_gradient_layer(R.ResNet[0].weights[0], R.ResNet[0].weights[1], R.tmp_layer_output[0], δ)
    
    #return δ + np.transpose(R.A(R.tmp_layer_output[0]).numpy()) + R.c.get_weights()[0]
    return δ 

Something is wrong with the 'whole' gradient?

In [20]:
Resnet = PINN_ResNet()

x = tf.constant([[1., 10.]])

out = Resnet(x)

δ = get_gradient_ResNet(Resnet)

print(δ)

δ_ad = _fvals1(Resnet, x)

print(δ_ad[1])

print(np.linalg.norm(δ - δ_ad[1]))

tf.Tensor(
[[ 0.02221752]
 [-0.00531843]], shape=(2, 1), dtype=float32)
[[ 0.0222175 ]
 [-0.00531846]]
3.3967748e-08


In [21]:
for i in range(5):
    x = tf.random.normal((1,2))
    Resnet = PINN_ResNet()
    out = Resnet(x)
    δ1 = get_gradient_ResNet(Resnet)
    δ_ad = _fvals1(Resnet, x)[1]
    print(np.linalg.norm(δ1-δ_ad))

2.0061302e-08
0.0
7.450581e-09
1.4901161e-08
1.8626451e-08


In [22]:
def get_gradient_hessian_layer_ResNet(W,b,a,δ):
    z1 = np.transpose(a @ W)  
    b = np.reshape(b, np.shape(z1))
    z2 = z1 + b
    z3 = np.diag(tf.reshape(mdσ(z2), [-1])) @ δ
    
    z4 = md2σ(z2) * δ
    ϑ = np.diag(tf.reshape(z4, [-1]))
    
    return W @ z3, W @ ϑ @ np.transpose(W)

In [23]:
def get_hessian_ResNet(R):
    δ,ϑ = get_gradient_hessian_layer_ResNet(R.ResNet[-1].weights[0], R.ResNet[-1].weights[1], R.tmp_layer_output[-1], R.wb.weights[0])

    δ = R.wb.weights[0] + R.ResNetStepsize * δ
 
    for k in range(R.ResNetLayers-2, 0, -1):
        δ_new, ϑ_new_1 = get_gradient_hessian_layer_ResNet(R.ResNet[k].weights[0], R.ResNet[k].weights[1], R.tmp_layer_output[k], δ)
        z1 = np.transpose(R.tmp_layer_output[k] @ R.ResNet[k].weights[0])  
        b = np.reshape(R.ResNet[k].weights()[1], np.shape(z1))
        z2 = z1 + b
        t1 = ϑ + R.ResNetStepsize * R.ResNet[k].weights[0] @ np.diag(tf.reshape(mdσ(z2), [-1])) @ ϑ
        ϑ_new_2 = np.transpose(t1) + R.ResNetStepsize * R.ResNet[k].weights[0] @ np.diag(tf.reshape(mdσ(z2), [-1])) @ np.transpose(t1)
        ϑ = ϑ_new_1 + ϑ_new_2
        δ = δ + R.ResNetStepsize * δ_new
    
      
    δ, ϑ = get_gradient_hessian_hidden_layer(R.ResNet[0].weights[0], R.ResNet[0].weights[1], R.tmp_layer_output[0], δ, ϑ)
    
    #return δ + np.transpose(R.A(R.tmp_layer_output[0]).numpy()) + R.c.get_weights()[0], ϑ + np.transpose(R.A.get_weights()[0])
    return δ, ϑ

In [24]:
for i in range(5):
    x = tf.random.normal((1,2))
    Resnet = PINN_ResNet()
    out = Resnet(x)
    δ,ϑ = get_hessian_ResNet(Resnet)
    ϑ_ad = _fvals2(Resnet, x)[2]
    print(np.linalg.norm(ϑ-ϑ_ad))

0.02004727
0.040664587
0.0139674535
0.007035735
0.002148037


In [25]:
Resnet.ResNet[0].weights[0]

<tf.Variable 'pinn__res_net_10/dense_134/kernel:0' shape=(2, 16) dtype=float32, numpy=
array([[-0.10830575,  0.3440271 , -0.47204584,  0.10250157,  0.2765507 ,
         0.3026178 , -0.4115299 ,  0.47118652, -0.2142457 , -0.4787906 ,
        -0.11594582, -0.12754828, -0.12051362, -0.05279261,  0.36103922,
         0.36242455],
       [ 0.53960454,  0.08977658,  0.30206776, -0.01997924, -0.40110546,
         0.10174572, -0.47245246,  0.49537158, -0.09396005, -0.10590637,
         0.27241457, -0.05103976, -0.2864606 , -0.0780122 , -0.2055957 ,
        -0.30557978]], dtype=float32)>